services:
  postgres:
    image: 'postgres'
    ports:
    - '5432:5432'
    restart: always
    environment:
    - POSTGRES_USER=user
    - POSTGRES_DB=masked_mails_development
    - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - postgres_data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      COLLECTOR_OTLP_ENABLED: 'true'
    ports:
    - '6831:6831/udp'
    - '6832:6832/udp'
    - '4317:4317'
    - '4318:4318'
    - '16686:16686'
    - '14268:14268'

volumes:
  postgres_data:
